#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function

import threading

from plano import *

script = ARGS[1]

broker0 = start_process("python python/broker.py {0} {1}", "127.0.0.1", 56720)
broker1 = start_process("python python/broker.py {0} {1}", "127.0.0.1", 56721)
broker2 = start_process("python python/broker.py {0} {1}", "127.0.0.1", 56722)

def run():
    sleep(5)

    stop_process(broker0)

    sleep(5)

    stop_process(broker1)

    sleep(5)

    stop_process(broker2)

thread = threading.Thread(target=run)
thread.start()

sleep(1)

ENV["PN_TRACE_FRM"] = "1"

client = start_process("{0} 127.0.0.1:56720 127.0.0.1:56721 127.0.0.1:56722", script)

thread.join()

stop_process(client)
