#!/usr/bin/python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from plano import *

def main():
    #set_message_threshold("warn")

    jar_file = join("qpid-jms", "target", "messaging-examples-jms-1.0.0-SNAPSHOT-jar-with-dependencies.jar")

    connection_url = ARGS[1]

    args = ["/usr/bin/env", "--", "java"]

    args += [
        "-Djava.naming.factory.initial=org.apache.qpid.jms.jndi.JmsInitialContextFactory",
        "-Dorg.slf4j.simpleLogger.defaultLogLevel=warn",
        "-classpath", jar_file,
        "net.ssorj.messaging.examples.jms.Connect",
        connection_url,
    ]

    args += ARGS[1:]

    exec_process(args)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
