name: main
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:focal
    steps:
    - run: |
        apt-get -qq update
        apt-get -qq install software-properties-common
        add-apt-repository -y ppa:qpid/released
        apt-get -qq update
        apt-get -qq install build-essential make openjdk-11-jdk maven nodejs python3 python3-numpy unzip xz-utils zstd
        apt-get -y install libqpid-proton-cpp12-dev python3-qpid-proton libsasl2-2 libsasl2-dev libsasl2-modules sasl2-bin
        npm install -g rhea
    - uses: actions/checkout@v2
    - run: make install PYTHON_EXECUTABLE=/usr/bin/python3
    # Missing: qpid-proton-ruby
    - run: equipage test pooled-jms qpid-jms qpid-proton-cpp qpid-proton-python rhea vertx-proton
      env: NODE_PATH=/usr/local/lib/node_modules
